/****************************************************************************************
File Name   : gold_aggregation_analysis.sql
Project     : Modern Data Warehouse with SQL Server
Layer       : Gold (Analytics & Business Insights)
Author      : Abdelkarim

Description :
    This script contains analytical queries designed to generate
    business insights from the Gold layer of the data warehouse.

    The focus is on:
    - Customer distribution by geography and demographics
    - Product distribution and cost analysis
    - Revenue contribution by category and customer
    - Sales volume distribution across countries

    These queries support:
    - Business performance analysis
    - Market segmentation
    - Strategic decision-making
    - Executive reporting and dashboards

****************************************************************************************/


/* =============================================================================
   CUSTOMER ANALYSIS
============================================================================= */

-- Analyze total number of customers by country
-- Helps identify key markets and geographic concentration
SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Analyze total number of customers by gender
-- Useful for demographic analysis and segmentation
SELECT 
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


/* =============================================================================
   PRODUCT ANALYSIS
============================================================================= */

-- Analyze total number of products by category
-- Helps understand product portfolio distribution
SELECT 
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- Analyze average product cost by category
-- Used to compare cost structures across product categories
SELECT 
	category,
	AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;


/* =============================================================================
   REVENUE ANALYSIS
============================================================================= */

-- Analyze total revenue generated by product category
-- Identifies top-performing product categories
SELECT 
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Analyze total revenue generated by each customer
-- Useful for identifying high-value customers
SELECT 
	c.customer_number,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON c.customer_key = f.customer_key
GROUP BY c.customer_number
ORDER BY total_revenue DESC;


/* =============================================================================
   SALES VOLUME & GEOGRAPHIC DISTRIBUTION
============================================================================= */

-- Analyze distribution of sold quantities across countries
-- Highlights countries with the highest sales volume
SELECT 
	c.country,
	SUM(f.quantity) AS total_quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC;
